apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ikclasses-webapp
  name: webapp
  namespace: prod-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ikclasses-webapp
  template:
    metadata:
      labels:
        app: ikclasses-webapp
    spec:
      containers:
      - image: imrankhetani/ikc:v5
        name: web-pods
