apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-ns
  name: my-ns
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    app: httpd-frontend
  type: NodePort