#labeling a node
# kubectl label nodes <node-name> <label-key>=<label-value>
# e.g. kubectl label nodes node-1 size=Large

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  -  image: data-processor
     name: data-processor
  nodeSelector:
    size: Large

# kubectl create -f node-selector.yaml